Improve CS.
Update LICENSE.

Use new version of "timonier/dumb-entrypoint".

Use "openjdk:jre-alpine" insteadof "alpine:3.4".

Use "timonier/version-lister".

diff --git a/src/rootfs/etc/cont-init.d/01-initialize-davmail b/src/rootfs/etc/cont-init.d/01-initialize-davmail
--- a/src/rootfs/etc/cont-init.d/01-initialize-davmail
+++ b/src/rootfs/etc/cont-init.d/01-initialize-davmail
@@ -1,7 +1,8 @@
-#!/usr/bin/with-contenv /bin/sh
+#!/bin/sh
+set -e
 
 if [ -z "${URL}" ] ; then
-    echo "Environment variable URL is missing." 1>&2
+    echo 1>&2 "Environment variable URL is missing."
     exit 1
 fi
 sed -i "s@%URL%@${URL}@g" /etc/davmail/davmail.properties
