Update LICENSE to 2017.
Improve README.

Escape bash variables.

Remove "MAINTAINER" instruction.

diff --git a/src/rootfs/etc/cont-init.d/01-initialize-davmail b/src/rootfs/etc/cont-init.d/01-initialize-davmail
--- a/src/rootfs/etc/cont-init.d/01-initialize-davmail
+++ b/src/rootfs/etc/cont-init.d/01-initialize-davmail
@@ -1,5 +1,9 @@
 #!/usr/bin/with-contenv /bin/sh
 
+if [ -z "${URL}" ] ; then
+    echo "Environment variable URL is missing." 1>&2
+    exit 1
+fi
 sed -i "s@%URL%@${URL}@g" /etc/davmail/davmail.properties
 
 sed -i "s@%PORT_CALDAV%@${PORT_CALDAV:-1080}@g" /etc/davmail/davmail.properties
